"""
Implementation of the "patchelf" command.

Credit to AngheloAlf for the original implementation, which is licensed under MIT.
"""

import argparse
import logging
import struct
from pathlib import Path

from build_system.env import Environment

import spimdisasm

LOG = logging.getLogger(__name__)

_SECTIONS: dict[str, int] = {
    # This is 0x08 for ELFs generated by old GCC, but some of the
    # `newlib` R5900 ASM TUs have 0x04 alignment. It doesn't break anything
    # right now to leave this at `0x04`. If we see strange issues in later TUs,
    # we'll want to use `0x08` globally and `0x04` just for the newlib ASM.
    ".text": 0x04,
    # TODO: make sure this is correct.
    ".data": 0x04,
    ".bss": 0x10,
    ".sbss": 0x04,
    ".sdata": 0x04,
    ".rodata": 0x10,
}


def add_subparser(subparsers):
    """
    Add the argument parser for the command to the action object for
    the main parser.
    """
    parser: argparse.ArgumentParser = subparsers.add_parser(
        "patchelf",
        help="Fixes the section alignment in `.o` ELFs generated by modern GAS.",
        description="Fixes the section alignment in `.o` ELFs generated by modern GAS.",
    )
    parser.add_argument(
        "elf_path", help="Path to ELF to patch alignments for.", type=Path
    )
    parser.set_defaults(func=_patchelf_cli)


def _patchelf_cli(env: Environment, args):
    """
    Handle the "patchelf" command of the CLI.
    """
    patchelf(env, args.elf_path)


def patchelf(env: Environment, elf: Path):
    """
    Fix the section alignment in a `.o` ELF file generated by modern GAS.
    """
    elf_contents = bytearray(elf.read_bytes())
    elf_file = spimdisasm.elf32.Elf32File(elf_contents)

    for i, sect in enumerate(elf_file.sectionHeaders):
        section_name: str = elf_file.shstrtab[sect.name]

        alignment = _SECTIONS.get(section_name)
        if alignment is not None:
            section_offset = elf_file.header.shoff + i * 0x28
            addralign_ptr = section_offset + 0x20

            # Patch the alignment.
            fmt = spimdisasm.common.GlobalConfig.ENDIAN.toFormatString() + "I"
            struct.pack_into(fmt, elf_contents, addralign_ptr, alignment)

    elf.write_bytes(elf_contents)
