"""
Implementation of the "patchelf" command.

Credit to AngheloAlf for the original implementation, which is licensed under MIT.
"""

import argparse
import logging
import struct
from pathlib import Path

from build_system.env import Environment

import spimdisasm

LOG = logging.getLogger(__name__)

_SECTIONS: dict[str, int] = {
    ".text": 0x08,
    # TODO: make sure this is correct.
    ".data": 0x04,
    # ".bss": 0x10,
    ".bss": 0x08,
    ".sbss": 0x04,
    ".sdata": 0x04,
    ".rodata": 0x08,
}

_FILE_SECTIONS_OVERRIDE: dict[str, dict[str, int]] = {
    # newlib/libc/machine/r5900/
    "memcpy.s.o": {".text": 0x04},
    "memset.s.o": {".text": 0x04},
    "strcat.s.o": {".text": 0x04},
    "strchr.s.o": {".text": 0x04},
    "strcmp.s.o": {".text": 0x04},
    "strcpy.s.o": {".text": 0x04},
    "strlen.s.o": {".text": 0x04},
    "strncat.s.o": {".text": 0x04},
    "strncpy.s.o": {".text": 0x04},
    "memchr.s.o": {".text": 0x04},
    "memmove.s.o": {".text": 0x04},
    "memcmp.s.o": {".text": 0x04},
}


def add_subparser(subparsers):
    """
    Add the argument parser for the command to the action object for
    the main parser.
    """
    parser: argparse.ArgumentParser = subparsers.add_parser(
        "patchelf",
        help="Fixes the section alignment in `.o` ELFs generated by modern GAS.",
        description="Fixes the section alignment in `.o` ELFs generated by modern GAS.",
    )
    parser.add_argument(
        "elf_path", help="Path to ELF to patch alignments for.", type=Path
    )
    parser.set_defaults(func=_patchelf_cli)


def _patchelf_cli(env: Environment, args):
    """
    Handle the "patchelf" command of the CLI.
    """
    patchelf(env, args.elf_path)


def patchelf(env: Environment, elf: Path):
    """
    Fix the section alignment in a `.o` ELF file generated by modern GAS.
    """
    elf_contents = bytearray(elf.read_bytes())
    elf_file = spimdisasm.elf32.Elf32File(elf_contents)

    for i, sect in enumerate(elf_file.sectionHeaders):
        section_name: str = elf_file.shstrtab[sect.name]

        alignment = _SECTIONS.get(section_name)
        overrides = _FILE_SECTIONS_OVERRIDE.get(elf.name)
        if overrides is not None:
            if overrides.get(section_name) is not None:
                alignment = overrides[section_name]

        if alignment is not None:
            section_offset = elf_file.header.shoff + i * 0x28
            addralign_ptr = section_offset + 0x20

            # Patch the alignment.
            fmt = spimdisasm.common.GlobalConfig.ENDIAN.toFormatString() + "I"
            struct.pack_into(fmt, elf_contents, addralign_ptr, alignment)

    elf.write_bytes(elf_contents)
