name: SCUS_971.01
sha1: be9859150dccc8589bfb5fc4e798fee7b7c9b6ee
options:
  platform: ps2
  compiler: EEGCC
  basename: SCUS_971.01
  base_path: ../..
  target_path: disks/SCUS_971.01.rom
  asm_path: asm
  src_path: src
  ld_script_path: config/US/SCUS_971.01.ld
  cache_path: config/US/.splache
  symbol_addrs_path: config/US/symbol_addrs.txt
  reloc_addrs_path: config/US/reloc_addrs.txt
  undefined_funcs_auto_path: config/US/undefined_funcs.txt
  undefined_syms_auto_path: config/US/undefined_syms_auto.txt
  # extensions_path: tools/splat_ext
  nonmatchings_path: nonmatchings

  find_file_boundaries: False
  gp_value: 0x004FEE70
  use_legacy_include_asm: False
  section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
  auto_link_sections: []
  create_undefined_funcs_auto: False
  create_undefined_syms_auto: False
  do_c_func_detection: True
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  ld_bss_is_noload: True
  subalign: null
  migrate_rodata_to_functions: True
  named_regs_for_c_funcs: False
  use_gp_rel_macro_nonmatching: False
  disassemble_all: True

segments:
  - name: main
    type: code
    start: 0x0
    vram: 0x00100000
    bss_size: 0x255E1C
    align: 4
    subsegments:
      # ------------------------------------------------
      # .text segment (C/C++ code)
      # ------------------------------------------------
      - [0x0000, asm, gcc/_crt0]
      - [0x00C0, asm, tmb/ai]
      - [0x82D8, asm, gcc/reg_frame] # C:\TEMP\ccEdaaaa.c - likely autogenerated by G++
      - [0x8350, asm, tmb/attach]
      - [0x8AF8, asm, tmb/attract]
      - [0x9BB0, asm, tmb/attracti]
      - [0xB120, asm, tmb/attractped]
      - [0xE0D0, asm, tmb/axle]
      - [0xE8D0, asm, tmb/blimp]
      - [0x0F1C0, asm, tmb/boss]
      - [0x12378, asm, tmb/burnman]
      - [0x12E50, asm, tmb/camera]
      - [0x15110, asm, tmb/city]
      - [0x151D8, asm, tmb/clapper]
      - [0x15B48, asm, tmb/collis]
      - [0x1C718, cpp, tmb/combo]
      - [0x1F8E8, asm, tmb/db]
      - [0x20020, asm, tmb/death2]
      - [0x20078, asm, tmb/death3]
      - [0x20228, asm, tmb/debris]
      - [0x21298, asm, tmb/destruct]
      - [0x25740, asm, tmb/prison_h] # prison.h inlines
      - [0x25748, asm, tmb/drivein]
      - [0x25BB8, asm, tmb/driver]
      - [0x28A78, asm, tmb/elevator]
      - [0x29568, asm, tmb/envheli]
      - [0x2A3B8, asm, tmb/ferris]
      - [0x2ACC8, asm, tmb/flipbufferi]
      - [0x2ADF0, asm, tmb/fodder]
      - [0x2BDE0, asm, tmb/fodderdriver]
      - [0x2CE70, asm, tmb/forceField]
      - [0x2D858, asm, tmb/freeway]
      - [0x2E200, asm, tmb/freewaytrain]
      - [0x2EA70, asm, tmb/game]
      - [0x359E8, asm, tmb/gastank]
      - [0x36468, asm, tmb/grim]
      - [0x36C70, asm, tmb/healthstand]
      - [0x37BD8, asm, tmb/helicop]
      - [0x39580, asm, tmb/heliptool]
      - [0x39708, asm, tmb/highway]
      - [0x39908, asm, tmb/highwaydriver]
      - [0x3AAB8, asm, tmb/highwayptool]
      - [0x3ACA0, asm, tmb/hud]
      - [0x42CD8, asm, tmb/hwyloop]
      - [0x42D08, asm, tmb/interact]
      - [0x430F0, asm, tmb/junkjet]
      - [0x44098, asm, tmb/junkyard]
      - [0x44FF0, asm, tmb/launch]
      - [0x515D8, asm, tmb/looptank]
      - [0x52250, asm, tmb/ped]
      - [0x53A20, asm, tmb/pedptool]
      - [0x53D90, asm, tmb/pickup]
      - [0x565D8, asm, tmb/pickupptool]
      - [0x566F8, asm, tmb/player]
      - [0x57A60, asm, tmb/prison]
      - [0x59948, asm, tmb/prisonShip]
      - [0x59CA8, asm, tmb/rigiddebris]
      - [0x5B450, asm, tmb/rt]
      - [0x5BD90, asm, tmb/reset]
      - [0x5CA70, asm, tmb/rooftop]
      - [0x5DE98, asm, tmb/shadow]
      - [0x5E5F8, asm, tmb/shell]
      - [0x63500, asm, tmb/shelloverlays]
      - [0x68180, asm, tmb/skidmark]
      - [0x69960, asm, tmb/smasher]
      - [0x6A040, asm, tmb/sound]
      - [0x870A0, asm, tmb/suburb]
      - [0x87530, asm, tmb/susp]
      - [0x88BB0, asm, tmb/tankcar]
      - [0x89040, asm, tmb/thunderstorm]
      - [0x89580, asm, tmb/timberdebris]
      - [0x89C90, asm, tmb/tire]
      - [0x8BCE8, asm, tmb/tmmemcard]
      - [0x8CD68, asm, tmb/trafficdirector]
      - [0x8E948, asm, tmb/ui]
      - [0x9E358, asm, tmb/uimemcard]
      - [0xA3B98, asm, tmb/vehicle]
      - [0xB08E0, asm, tmb/watow]
      - [0xB0D60, asm, tmb/weap]
      - [0xBACA0, asm, tmb/989snd]
      - [0xBCEC8, asm, tmb/aa]
      - [0xBD530, asm, tmb/animChan]
      - [0xBFF98, asm, tmb/bound]
      - [0xC00D0, asm, tmb/CsColor]
      - [0xC0248, asm, tmb/dbs] # this file has C++ STL inlines
      - [0xC1310, asm, tmb/disp]
      - [0xC1B20, asm, tmb/drawc]
      - [0xC21D0, asm, tmb/file]
      - [0xC36F8, asm, tmb/fog]
      - [0xC3E48, cpp, tmb/font]
      - [0xC4C38, asm, tmb/hd]
      - [0xC8D40, asm, tmb/hdcar]
      - [0xCEC90, asm, tmb/hdhat]
      - [0xD0288, asm, tmb/hdlos]
      - [0xD28E8, asm, tmb/hierc]
      - [0xD51E0, asm, tmb/hiertrav] # hiertrav.s - hand-coded ASM
      - [0xD5C08, asm, tmb/hoserInfo]
      - [0xD61A8, asm, tmb/ieGs]
      - [0xD6A78, asm, tmb/ilnk]
      - [0xD6BC0, asm, tmb/input]
      - [0xD9C30, asm, tmb/LightVolume]
      - [0xDA1E8, cpp, tmb/mathf]
      - [0xDCB90, asm, tmb/mathv0] # Might need to be `hasm`, seems to be inline assembly.
      - [0xDCDC8, asm, tmb/memCard]
      - [0xDED00, asm, tmb/memorystack]
      - [0xDED38, asm, tmb/movie]
      - [0xDF890, asm, tmb/particle]
      - [0xE9AD8, asm, tmb/pkt]
      - [0xEAAE8, asm, tmb/pkta] # pkta.s HASM
      - [0xEB030, asm, tmb/plight]
      - [0xEC2C8, asm, tmb/read]
      - [0xEC5F8, asm, tmb/readbuf]
      - [0xEC708, asm, tmb/resetcom]
      - [0xECF60, asm, tmb/rigidbody]
      - [0xEE1A8, asm, tmb/smooth]
      - [0xEE8D8, asm, tmb/strfile]
      - [0xEEAD8, asm, tmb/sys] # sys.s HASM
      - [0xEEB20, asm, tmb/td]
      - [0xEF3A0, asm, tmb/terrain]
      - [0xF6788, asm, tmb/timer]
      - [0xF6B58, asm, tmb/tod]
      - [0xF8868, asm, tmb/texm] # has C++ STL inlines
      - [0xFB9F0, asm, tmb/texa] # texa.s HASM
      - [0xFBD08, asm, tmb/utilities]
      - [0xFCA00, asm, tmb/view]
      - [0xFE590, asm, tmb/videodec]
      - [0xFED98, asm, tmb/vobuf]
      - [0xFEF78, asm, tmb/zip]
      - [0x100C08, asm, tmb/audiodec]
      - [0x101310, asm, tmb/bsp]
      - [0x101708, asm, tmb/charanim]
      - [0x101CD0, asm, tmb/ctx]
      - [0x101D70, asm, tmb/CsList]
      - [0x101E98, asm, tmb/hier] # hier.s HASM
      - [0x102160, asm, tmb/vibuf] # TODO: this is probably two TUs
      # SDK TUs start here
      - [0x1033B0, asm, sdk/libgraph/graphdev]
      - [0x104E80, asm, sdk/libpad/libpad]
      - [0x106228, asm, sdk/libmtap/libmtap]
      - [0x1066F8, asm, sdk/libmc/libmc]
      - [0x1078E0, asm, sdk/libmpeg/pack]
      - [0x1086B8, asm, sdk/libmpeg/mpeg]
      - [0x109278, asm, sdk/libmpeg/init]
      - [0x109E50, asm, sdk/libmpeg/defhandler]
      - [0x109E70, asm, sdk/libmpeg/mpc]
      - [0x10EBF0, asm, sdk/libmpeg/csc]
      - [0x10F098, asm, sdk/libmpeg/bit]
      - [0x10F2A8, asm, sdk/libipu/libipu]
      - [0x10F660, asm, sdk/libipu/ipuinit]
      - [0x10F8F8, asm, sdk/liblgdev/liblgdev]
      - [0x1107B8, asm, sdk/libcdvd/eecdvd]
      # C runtime TUs start here
      - [0x113530, asm, newlib/libm/math/sf_atan]
      - [0x1137D8, asm, newlib/libm/math/sf_ceil]
      - [0x1138B0, asm, newlib/libm/math/sf_cos]
      - [0x113998, asm, newlib/libm/math/sf_fabs]
      - [0x1139B8, asm, newlib/libm/math/sf_floor]
      - [0x113AA0, asm, newlib/libm/math/sf_sin]
      - [0x113B90, asm, newlib/libm/math/w_sqrt]
      - [0x113CA0, asm, newlib/libm/math/wf_atan2]
      - [0x113DC8, asm, newlib/libm/math/wf_pow]
      - [0x1142D0, asm, newlib/libm/math/wf_sqrt]
      - [0x1143E8, asm, newlib/libm/math/e_sqrt]
      - [0x1146F0, asm, newlib/libm/math/ef_atan2]
      - [0x1149D8, asm, newlib/libm/math/ef_pow]
      - [0x115268, asm, newlib/libm/math/ef_rem_pio2]
      - [0x115648, asm, newlib/libm/math/ef_sqrt]
      - [0x115780, asm, newlib/libm/math/kf_cos]
      - [0x1158D8, asm, newlib/libm/math/kf_rem_pio2]
      - [0x116228, asm, newlib/libm/math/kf_sin]
      - [0x116330, asm, newlib/libm/math/s_isnan]
      - [0x116368, asm, newlib/libm/math/s_matherr]
      - [0x116390, asm, newlib/libm/math/s_rint]
      - [0x116590, asm, newlib/libm/math/sf_finite]
      - [0x1165B8, asm, newlib/libm/math/sf_isnan]
      - [0x1165E0, asm, newlib/libm/math/sf_scalbn]
      - [0x116740, asm, newlib/libm/math/sf_copysign]
      - [0x116770, asm, gcc/libgcc2]
      - [0x117B48, asm, gcc/dp-bit]
      - [0x118858, asm, gcc/cp/exception] # exception.cc
      - [0x118F98, asm, gcc/fp-bit]
      - [0x119B78, asm, gcc/frame]
      - [0x11ABA8, asm, gcc/cp/new] # new.cc
      - [0x11AC58, asm, gcc/cp/new2] # new2.cc
      - [0x11ACD0, asm, gcc/cp/new1] # new1.cc
      - [0x11ADF8, asm, gcc/cp/tinfo] # tinfo.cc
      - [0x11B4C8, asm, gcc/cp/tinfo2] # tinfo2.cc
      - [0x11C248, asm, newlib/libc/stdlib/abort]
      - [0x11C268, asm, newlib/libc/stdlib/atexit]
      - [0x11C300, asm, newlib/libc/errno/errno]
      - [0x11C310, asm, newlib/libc/stdio/findfp]
      - [0x11C568, asm, newlib/libc/stdio/fwalk]
      - [0x11C600, asm, newlib/libc/stdlib/malloc]
      - [0x11C638, asm, newlib/libc/stdlib/mallocr]
      - [0x11D008, asm, newlib/libc/machine/r5900/memcpy] # memcpy.S HASM
      - [0x11D0B8, asm, newlib/libc/machine/r5900/memset] # memset.S HASM
      - [0x11D178, asm, newlib/libc/stdlib/mlock]
      - [0x11D188, asm, newlib/libc/stdio/printf]
      - [0x11D218, asm, newlib/libc/stdlib/rand]
      - [0x11D258, asm, newlib/libc/reent/sbrkr]
      - [0x11D2B8, asm, newlib/libc/signal/signal]
      - [0x11D608, asm, newlib/libc/reent/signalr]
      - [0x11D688, asm, newlib/libc/stdio/sprintf]
      - [0x11D760, asm, newlib/libc/stdio/stdio]
      - [0x11D8D0, asm, newlib/libc/machine/r5900/strcat] # strcat.S HASM
      - [0x11D9FC, asm, newlib/libc/machine/r5900/strchr] # strchr.S HASM
      - [0x11DB8C, asm, newlib/libc/machine/r5900/strcmp] # strcmp.S HASM
      - [0x11DCD0, asm, newlib/libc/machine/r5900/strcpy] # strcpy.S HASM
      - [0x11DDE4, asm, newlib/libc/machine/r5900/strlen] # strlen.S HASM
      - [0x11DF20, asm, newlib/libc/machine/r5900/strncat] # strncat.S HASM
      - [0x11E0D0, asm, newlib/libc/machine/r5900/strncpy] # strncpy.S HASM
      - [0x11E290, asm, newlib/libc/stdio/vfprintf]
      - [0x11FBB0, asm, newlib/libc/reent/writer]
      - [0x11FC10, asm, newlib/libc/stdio/wsetup]
      - [0x11FD20, asm, newlib/libc/reent/closer]
      - [0x11FD78, asm, newlib/libc/stdlib/dtoa]
      - [0x121160, asm, newlib/libc/stdio/fflush]
      - [0x121268, asm, newlib/libc/stdlib/mallocr_2] # TODO: why is this a different TU?
      - [0x1216F8, asm, newlib/libc/stdio/fvwrite]
      - [0x121AD0, asm, newlib/libc/locale/locale]
      - [0x121BC0, asm, newlib/libc/reent/lseekr]
      - [0x121C20, asm, newlib/libc/stdio/makebuf]
      - [0x121D70, asm, newlib/libc/stdlib/mbtowc_r]
      - [0x121DAC, asm, newlib/libc/machine/r5900/memchr] # memchr.S HASM
      - [0x121E8C, asm, newlib/libc/machine/r5900/memmove] # memmove.S HASM
      - [0x121F90, asm, newlib/libc/stdlib/mprec]
      - [0x122FB0, asm, newlib/libc/reent/readr]
      - [0x123010, asm, newlib/libm/math/s_isinf]
      - [0x123058, asm, newlib/libc/stdlib/mallocr_3] # TODO: why is this a different TU?
      - [0x123118, asm, newlib/libc/reent/fstatr]
      # Start of SDK libs again
      - [0x123180, asm, sdk/libkernl/klib] # klib.s HASM
      - [0x123A10, asm, sdk/libkernl/glue]
      - [0x123DB8, asm, sdk/libkernl/cache]
      - [0x124028, asm, sdk/libkernl/intr]
      - [0x124360, asm, sdk/libkernl/thread]
      - [0x1246C0, asm, sdk/libkernl/tty]
      - [0x124BE0, asm, sdk/libkernl/kprintf]
      - [0x125620, asm, sdk/libkernl/sifcmd]
      - [0x125D80, asm, sdk/libkernl/sifrpc]
      - [0x126CA8, asm, sdk/libkernl/filestub]
      - [0x1279C0, asm, sdk/libkernl/iopheap]
      - [0x127C20, asm, sdk/libkernl/eeloadfile]
      - [0x1284F0, asm, sdk/libkernl/iopreset]
      - [0x128790, asm, sdk/libkernl/deci2]
      - [0x128970, asm, gcc/libgcc2_2] # TODO: why is this a different TU?
      - [0x12A2C8, asm, newlib/libc/machine/r5900/memcmp] # memcmp.S HASM
      # ------------------------------------------------
      # .vutext segment
      # ------------------------------------------------
      - [0x12A360, data, vutext]
      # ------------------------------------------------
      # .data segment
      # ------------------------------------------------
      - [0x134D00, data]
      # ------------------------------------------------
      # .rodata segment
      # TODO: Many segments in here contain the string `Q210PedestrianStrategy`,
      # likely from `ped.h`. Determine which modules actually include that
      # header, and how to get the string into those modules.
      # ------------------------------------------------
      - [0x3E4780, rodata, tmb/ai]
      - [0x3E4968, rodata, tmb/attach]
      - [0x3E4A30, rodata, tmb/attracti]
      - [0x3E4B80, rodata, tmb/attractped]
      - [0x3E4BF8, rodata, tmb/axle]
      - [0x3E4C18, rodata, tmb/blimp]
      - [0x3E4C40, rodata, tmb/boss]
      - [0x3E4CA0, rodata, tmb/camera]
      - [0x3E4CE0, rodata, tmb/clapper]
      - [0x3E4D20, rodata, tmb/collis]
      - [0x3E4F40, rodata, tmb/destruct]
      - [0x3E5060, rodata, tmb/elevator]
      - [0x3E50D8, rodata, tmb/envheli]
      - [0x3E5100, rodata, tmb/ferris]
      - [0x3E5150, rodata, tmb/fodder]
      - [0x3E5200, rodata, tmb/forceField]
      - [0x3E5240, rodata, tmb/freeway]
      - [0x3E52E0, rodata, tmb/game]
      - [0x3E55E0, rodata, tmb/gastank]
      - [0x3E5638, rodata, tmb/grim]
      - [0x3E5660, rodata, tmb/healthstand]
      - [0x3E56C0, rodata, tmb/helicop]
      - [0x3E56F8, rodata, tmb/heliptool]
      - [0x3E5780, rodata, tmb/highwaydriver]
      - [0x3E57B8, rodata, tmb/highwayptool]
      - [0x3E5830, rodata, tmb/hud]
      - [0x3E6F40, rodata, tmb/interact]
      - [0x3E6F90, rodata, tmb/junkjet]
      - [0x3E6FD0, rodata, tmb/junkyard]
      - [0x3E7070, rodata, tmb/launch]
      - [0x3E7240, rodata, tmb/looptank]
      - [0x3E7350, rodata, tmb/ped]
      - [0x3E7458, rodata, tmb/pedptool]
      - [0x3E75E0, rodata, tmb/pickup]
      - [0x3E76E8, rodata, tmb/pickupptool]
      - [0x3E7740, rodata, tmb/player]
      - [0x3E7770, rodata, tmb/prison]
      - [0x3E77F0, rodata, tmb/prisonShip]
      - [0x3E7830, rodata, tmb/rigiddebris]
      - [0x3E78D8, rodata, tmb/reset]
      - [0x3E7910, rodata, tmb/rooftop]
      - [0x3E7A98, rodata, tmb/shadow]
      - [0x3E7AE0, rodata, tmb/shell]
      - [0x3E8118, rodata, tmb/shelloverlays]
      - [0x3E8A20, rodata, tmb/smasher]
      - [0x3E8A50, rodata, tmb/sound]
      - [0x3EAC20, rodata, tmb/suburb]
      - [0x3EAC90, rodata, tmb/susp]
      - [0x3EAD40, rodata, tmb/timberdebris]
      - [0x3EAD68, rodata, tmb/tire]
      - [0x3EAE30, rodata, tmb/tmmemcard]
      - [0x3EAE90, rodata, tmb/ui]
      - [0x3F0CD0, rodata, tmb/uimemcard]
      - [0x3F1900, rodata, tmb/vehicle]
      - [0x3F1AA0, rodata, tmb/weap]
      - [0x3F1D70, rodata, tmb/989snd]
      - [0x3F1E80, rodata, tmb/animChan]
      - [0x3F1EB8, rodata, tmb/CsColor]
      - [0x3F1EF0, rodata, tmb/dbs]
      - [0x3F20D0, rodata, tmb/file]
      - [0x3F2230, .rodata, tmb/font]
      - [0x3F2298, rodata, tmb/hd]
      - [0x3F2440, rodata, tmb/hdcar]
      - [0x3F2750, rodata, tmb/hdhat]
      - [0x3F2860, rodata, tmb/hdlos]
      - [0x3F2990, rodata, tmb/hierc]
      - [0x3F2A30, rodata, tmb/hoserInfo]
      - [0x3F2A50, rodata, tmb/input]
      - [0x3F2D30, .rodata, tmb/mathf]
      - [0x3F2D88, rodata, tmb/memCard]
      - [0x3F2FB0, rodata, tmb/movie]
      - [0x3F2FF0, rodata, tmb/particle]
      - [0x3F31D8, rodata, tmb/read]
      - [0x3F31F0, rodata, tmb/resetcom]
      - [0x3F33D0, rodata, tmb/strfile]
      - [0x3F3400, rodata, tmb/td]
      - [0x3F3470, rodata, tmb/terrain]
      - [0x3F3518, rodata, tmb/texm]
      - [0x3F35B0, rodata, tmb/view]
      - [0x3F3608, rodata, tmb/videodec]
      - [0x3F3630, rodata, tmb/zip]
      - [0x3F4198, rodata, tmb/vibuf]
      # SDK/GCC/newlib rodata past this point.
      - [0x3F41B0, rodata]
      # ------------------------------------------------
      # .gcc_except_table segment
      # ------------------------------------------------
      - [0x3F6D80, rodatabin, gcc_except_table]
      # ------------------------------------------------
      # .lit4 segment
      # ------------------------------------------------
      - [0x3F6E80, lit4]
      - [0x3FA64C, .lit4, tmb/mathf]
      - [0x3FA690, lit4]
      # ------------------------------------------------
      # .sdata segment
      # ------------------------------------------------
      - [0x3FA900, sdata]
      - [0x3FAB3C, sdata, tmb/launch]
      - [0x3FAC14, sdata]
      - [0x3FB840, .sdata, tmb/font]
      - [0x3FB850, sdata, tmb/hd]
      - [0x3FB86C, sdata, tmb/hdcar]
      - [0x3FB888, sdata, tmb/hdhat]
      - [0x3FB88C, sdata, tmb/hdlos]
      - [0x3FB8A4, sdata]
      # ------------------------------------------------
      # .sbss segment
      # ------------------------------------------------
      - {type: sbss, vram: 0x004FBD00, name: sbss1}
      - {type: .sbss, vram: 0x004FBD08, name: tmb/combo}
      - {type: sbss, vram: 0x004FBD44, name: sbss2}
      - {type: .sbss, vram: 0x004FBE34, name: tmb/font}
      - {type: sbss, vram: 0x004FBE48, name: sbss3}
      # ------------------------------------------------
      # .bss segment
      # ------------------------------------------------
      - {type: bss, vram: 0x004FC000, name: bss1}
      - {type: .bss, vram: 0x00504480, name: tmb/font}
      - {type: bss, vram: 0x00510100, name: bss2}

  - [0x3FBD00] # end of file
  # ------------------------------------------------
  # Debug info segments
  # ------------------------------------------------
#  - [0x3FCD00, databin] # padding to .reginfo
#  - [0x3FCD14, databin] # .reginfo
#  - [0x3FCD2C, databin] # .mdebug
#  - [0x4F2F70, databin] # .DVP_ovlytab
#  - [0x4F3030, databin] # .DVP_ovlystrtab
#  - [0x4F324C, databin] # .DVP_overlay__0x0_13651_30_0
#  - [0x4F3A4C, databin] # .DVP_overlay__unknvma_31515_777_1
#  - [0x4F424C, databin] # .DVP_overlay__unknvma_31515_1315_2
#  - [0x4F4A4C, databin] # .DVP_overlay__unknvma_31515_1747_3
#  - [0x4F524C, databin] # .DVP_overlay__unknvma_31515_2637_4
#  - [0x4F5A4C, databin] # .DVP_overlay__unknvma_31515_3061_5
#  - [0x4F5A6C, databin] # .DVP_overlay__0x0_28451_38_0
#  - [0x4F626C, databin] # .DVP_overlay__unknvma_61707_538_1
#  - [0x4F6A6C, databin] # .DVP_overlay__unknvma_61707_1141_2
#  - [0x4F726C, databin] # .DVP_overlay__unknvma_61707_1760_3
#  - [0x4F7A6C, databin] # .DVP_overlay__unknvma_61707_2182_4
#  - [0x4F826C, databin] # .DVP_overlay__unknvma_61707_2668_5
#  - [0x4F8A6C, databin] # .DVP_overlay__unknvma_61707_3109_6
#  - [0x4F8F8C, databin] # .DVP_overlay__0x0_27859_18_0
#  - [0x4F96BC, databin] # .DVP_overlay__0x0_13171_23_0
#  - [0x4F9EBC, databin] # .DVP_overlay__unknvma_31035_529_1
#  - [0x4FA2F4, databin] # .shstrtab
#  - [0x4FA5AC, databin] # .elfSectionHeaders
#  - [0x4FAB4C, databin] # .symtab
#  - [0x518A8C, databin] # .strtab
#  - [0x53C14F] # End of file
